#!/bin/sh

# adjust paths
OPTEE_OS_DIR=/d1/op-tee/optee_os-rpi4
OPTEE_CLIENT_DIR=/d1/buildroot/build/linux-rpi/build/optee-client-3.18.0
CC=/opt/toolchain/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-

mkdir -p build

${CC}c++ client.cpp \
  -I${OPTEE_CLIENT_DIR}/public \
  -L${OPTEE_CLIENT_DIR}/libteec \
  -lteec \
  -std=c++20 \
  -o build/tls-example-client

make \
  CROSS_COMPILE64=${CC} \
  TA_DEV_KIT_DIR=${OPTEE_OS_DIR}/out/arm-plat-rpi4/export-ta_arm64 \
  CFG_TEE_TA_LOG_LEVEL=3 \
  O=build/client-ta
