#!/bin/sh

# adjust paths
OPTEEOS_DIR=/d1/op-tee/optee_os-rpi4
OPTEECLIENT_DIR=/d1/buildroot/build/linux-rpi/build/optee-client-3.18.0
CC=/opt/toolchain/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-

mkdir -p build

${CC}c++ client.cpp \
  -I${OPTEECLIENT_DIR}/public \
  -L${OPTEECLIENT_DIR}/libteec \
  -lteec \
  -o build/client

make \
  CROSS_COMPILE64=${CC} \
  TA_DEV_KIT_DIR=${OPTEEOS_DIR}/out/arm-plat-rpi4/export-ta_arm64 \
  CFG_TA_ASLR=n \
  CFG_TEE_TA_LOG_LEVEL=3 \
  DEBUG=1 \
  O=build/client-ta
